### ISSUE TITLE
Linux: streamlink_helper.py contains CR characters

### ISSUE THREAD

**Issue by Hofi** [plneappl/streamlink-helper#5] opened 2018-01-16 16:17 UTC
Hello,
I needed to remove CR characters from the file in order to make it work in Linux.
I got the "An unexpected error occurred" error in Console.
For example you can convert it with vim (:set ff=unix)
After I removed the CR characters it worked as expected.

**Comment by plneappl** [comment] 2018-01-18 18:14
I'm sorry but I can't reproduce this, all files I searched have only \n line-endings, no \r. Where exactly did you get the `streamlink_helper.py`-file from?

**Comment by Hofi** [comment] 2018-01-18 18:47
https://github.com/plneappl/streamlink-helper/releases/download/1.1.1.3/streamlink_helper.zip

> $ file streamlink_helper.py 
> streamlink_helper.py: Python script, ASCII text executable, with CRLF line terminators

**Comment by plneappl** [comment] 2018-01-18 18:53
Huh, I have a strange text editor it seems :) Fixed now, thanks!

**Closed as completed by plneappl** 2018-01-18 18:53 UTC
